version: "3.8"
services:
  mongo-auth:
    image: mongo:6
    container_name: mongo-auth
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-auth-data:/data/db

volumes:
  mongo-auth-data:
